version: "3.8"

services:
  app:
    build: .
    container_name: chigirh-app-trainning-liubang
    tty: true
    ports:
      - 80:3000
    volumes:
      - ./react-app:/react-app
    networks:
      - default
    command: sh -c "npm start"